# Generated by Django 5.2.1 on 2025-06-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_cliente_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
